### ISSUE TITLE
I want use the pointer in the register of ebp,when pass ebp to arglist,it crashed. why?

### ISSUE THREAD

**Issue by fengchuan1021** [cosine0/dllhook#1]
it looks like this:
import ctypes
import dllhook
@dllhook.hook_dll('some.dll', 0x329743)
def see_process(ebp):
	print(ebp);

when i don't give ebp to the arglist,it works fine. so my question is . how can i use the data in the register ebp or esp.

**Comment by cosine0** [comment]
Thank you for reporting this!
I'm planning to refactor and add features to this repo soon. So I'll check that when I'm working on it.

**Comment by fengchuan1021** [comment]
thanks your code. I found the reason of crashed is that stack is not balanced,when use the register. so add a var to count the regsiter used times.  
135:  
```
        stack_arg_count = 0
        fetchable_registers_arg_count=0
        for arg_name in argspec.args:
            if arg_name not in fetchable_registers:
                stack_arg_count += 1
            else:
                fetchable_registers_arg_count+=1
```
and in line 194:  
```
'''.format(count=invoker_count, before_call='\n'.join(invoker_c_asm), callbacker=callbacker_c_address,
           arg_depth=4 * (stack_arg_count+fetchable_registers_count), original_asm='\n'.join(original_asm),
           target_resume=target_address + total_length)
```

**Comment by cosine0** [comment]
Thanks for your advice. I fixed it accordingly!
